main: ${groupId}.${artifactId}.${name}
name: ${name}
version: ${version}
description: A bukkit plugin
author: [Rayzr]
#commands:
#  ${artifactId}:
#    description: ${name} main command
#    aliases: [alias1,alias2]
#    usage: "/${artifactId} [command]"
#    permission: ${name}.main
